# Makefile.in generated by automake 1.11.1 from Makefile.am.
# src/Foo1/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/banshee-community-extensions
pkgincludedir = $(includedir)/banshee-community-extensions
pkglibdir = $(libdir)/banshee-community-extensions
pkglibexecdir = $(libexecdir)/banshee-community-extensions
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
DIST_COMMON = README $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
	$(top_srcdir)/build/build.environment.mk \
	$(top_srcdir)/build/build.mk \
	$(top_srcdir)/build/build.rules.mk
#am__append_1 = " $(NUNIT_LIBS) $(MONO_NUNIT_LIBS)"
subdir = src/Foo1
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/build/m4/extensions/alarmclock.m4 \
	$(top_srcdir)/build/m4/extensions/ampache.m4 \
	$(top_srcdir)/build/m4/extensions/appindicator.m4 \
	$(top_srcdir)/build/m4/extensions/awn.m4 \
	$(top_srcdir)/build/m4/extensions/banshee.m4 \
	$(top_srcdir)/build/m4/extensions/clutterflow.m4 \
	$(top_srcdir)/build/m4/extensions/common.m4 \
	$(top_srcdir)/build/m4/extensions/coverwallpaper.m4 \
	$(top_srcdir)/build/m4/extensions/jamendo.m4 \
	$(top_srcdir)/build/m4/extensions/karaoke.m4 \
	$(top_srcdir)/build/m4/extensions/lastfmfingerprint.m4 \
	$(top_srcdir)/build/m4/extensions/lcd.m4 \
	$(top_srcdir)/build/m4/extensions/lirc.m4 \
	$(top_srcdir)/build/m4/extensions/liveradio.m4 \
	$(top_srcdir)/build/m4/extensions/lyrics.m4 \
	$(top_srcdir)/build/m4/extensions/magnatune.m4 \
	$(top_srcdir)/build/m4/extensions/mirage.m4 \
	$(top_srcdir)/build/m4/extensions/openvp.m4 \
	$(top_srcdir)/build/m4/extensions/radiostationfetcher.m4 \
	$(top_srcdir)/build/m4/extensions/randombylastfm.m4 \
	$(top_srcdir)/build/m4/extensions/streamrecorder.m4 \
	$(top_srcdir)/build/m4/extensions/telepathy.m4 \
	$(top_srcdir)/build/m4/extensions/zeitgeistdp.m4 \
	$(top_srcdir)/build/m4/shave/shave.m4 \
	$(top_srcdir)/build/m4/shamrock/expansions.m4 \
	$(top_srcdir)/build/m4/shamrock/gnome-doc.m4 \
	$(top_srcdir)/build/m4/shamrock/i18n.m4 \
	$(top_srcdir)/build/m4/shamrock/mono.m4 \
	$(top_srcdir)/build/m4/shamrock/nunit.m4 \
	$(top_srcdir)/build/m4/shamrock/programs.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(moduledir)"
SCRIPTS = $(module_SCRIPTS)
DIST_SOURCES =
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/thomas/banshee-community-extensions/missing --run aclocal-1.11
ACLOCAL_AMFLAGS = -I build/m4/shamrock -I build/m4/shave -I build/m4/extensions ${ACLOCAL_FLAGS}
ALL_LINGUAS = de el es fi fr it pt ru_RU sk uk_UA
AMTAR = ${SHELL} /home/thomas/banshee-community-extensions/missing --run tar
AM_MAKEFLAGS = `test -z $V && echo -s`
APPINDICATORSHARP_CFLAGS = 
APPINDICATORSHARP_LIBS = 
AR = ar
AUTOCONF = ${SHELL} /home/thomas/banshee-community-extensions/missing --run autoconf
AUTOHEADER = ${SHELL} /home/thomas/banshee-community-extensions/missing --run autoheader
AUTOMAKE = ${SHELL} /home/thomas/banshee-community-extensions/missing --run automake-1.11
AWK = gawk
BANSHEE_CFLAGS = -I:/usr/lib/pkgconfig/../../share/gapi-2.0/glib-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/pango-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/atk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gdk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gtk-api.xml  
BANSHEE_EXTDIR = /usr/lib/banshee/Extensions
BANSHEE_LASTFM_CFLAGS =  
BANSHEE_LASTFM_LIBS = -r:System -r:Mono.Posix -r:ICSharpCode.SharpZipLib -r:/usr/lib/banshee/Lastfm.dll -r:/usr/lib/banshee/Mono.Media.dll -r:/usr/lib/banshee/Hyena.dll  
BANSHEE_LIBDIR = /usr/lib/banshee
BANSHEE_LIBS = -r:/usr/lib/banshee/Banshee.Widgets.dll -r:/usr/lib/banshee/Banshee.ThickClient.dll -r:/usr/lib/banshee/Banshee.Services.dll -r:Mono.Cairo -r:/usr/lib/banshee/Hyena.Gui.dll -r:/usr/lib/banshee/Banshee.Core.dll -r:System -r:/usr/lib/banshee/Mono.Media.dll -r:/usr/lib/cli/NDesk.DBus-1.0/NDesk.DBus.dll -r:/usr/lib/cli/NDesk.DBus.GLib-1.0/NDesk.DBus.GLib.dll -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll -r:/usr/lib/cli/Mono.Addins-0.2/Mono.Addins.dll -r:Mono.Posix -r:/usr/lib/banshee/Hyena.dll -r:/usr/lib/banshee/Hyena.Data.Sqlite.dll -r:/usr/lib/banshee/MusicBrainz.dll -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll -r:/usr/lib/cli/taglib-sharp-2.0/taglib-sharp.dll  
BANSHEE_NOWPLAYING_CFLAGS =  
BANSHEE_NOWPLAYING_LIBS = -r:/usr/lib/banshee/Extensions/Banshee.NowPlaying.dll  
BANSHEE_WEBBROWSER_CFLAGS = -I:/usr/lib/pkgconfig/../../share/gapi-2.0/glib-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/pango-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/atk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gdk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gtk-api.xml  
BANSHEE_WEBBROWSER_LIBS = -r:/usr/lib/banshee/Banshee.WebBrowser.dll -r:/usr/lib/banshee/Banshee.Services.dll -r:Mono.Cairo -r:/usr/lib/banshee/Hyena.Gui.dll -r:/usr/lib/banshee/Banshee.Widgets.dll -r:/usr/lib/banshee/Banshee.ThickClient.dll -r:/usr/lib/banshee/Banshee.Core.dll -r:System -r:/usr/lib/banshee/Mono.Media.dll -r:/usr/lib/cli/NDesk.DBus-1.0/NDesk.DBus.dll -r:/usr/lib/cli/NDesk.DBus.GLib-1.0/NDesk.DBus.GLib.dll -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll -r:/usr/lib/cli/Mono.Addins-0.2/Mono.Addins.dll -r:Mono.Posix -r:/usr/lib/banshee/Hyena.dll -r:/usr/lib/banshee/Hyena.Data.Sqlite.dll -r:/usr/lib/banshee/MusicBrainz.dll -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll -r:/usr/lib/cli/taglib-sharp-2.0/taglib-sharp.dll  
BUILD_HOST_CPU = i686
BUILD_HOST_OS = linux-gnu
BUILD_TIME = 2011-09-20 11:42:49 CEST
BUILD_VENDOR_ID = git-checkout
CATALOGS =  de.gmo el.gmo es.gmo fi.gmo fr.gmo it.gmo pt.gmo ru_RU.gmo sk.gmo uk_UA.gmo
CATOBJEXT = .gmo
CC = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave cc gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CLUTTER_BUNDLEFILES = 
CLUTTER_SHARP_CFLAGS = 
CLUTTER_SHARP_LIBS = 
CONFIG_STATUS_DEPENDENCIES = $(top_srcdir)/po/LINGUAS
CPP = gcc -E
CPPFLAGS = 
CXX = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave cxx g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DATADIRNAME = share
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DISTCHECK_CONFIGURE_FLAGS = --disable-scrollkeeper --enable-release --enable-tests
DOC_USER_FORMATS = 
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENABLE_RELEASE = no
EXEEXT = 
EXTENSION_DIR = ${exec_prefix}/lib/banshee/Extensions
F77 = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave f77 
FC = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave fc 
FFTW3F_CFLAGS = 
FFTW3F_LIBS = 
FGREP = /bin/grep -F
GCONFSHARP_CFLAGS =  
GCONFSHARP_LIBS = -r:/usr/lib/cli/gconf-sharp-2.0/gconf-sharp.dll  
GCONFTOOL = /usr/bin/gconftool-2
GCONF_SCHEMA_CONFIG_SOURCE = xml:merged:/etc/gconf/gconf.xml.defaults
GCONF_SCHEMA_FILE_DIR = $(sysconfdir)/gconf/schemas
GCONF_SHARP_20_CFLAGS =  
GCONF_SHARP_20_LIBS = -r:/usr/lib/cli/gconf-sharp-2.0/gconf-sharp.dll  
GETTEXT_PACKAGE = banshee-community-extensions
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
GLIB_LIBS = -lglib-2.0  
GMCS_FLAGS = -unsafe
GMOFILES =  de.gmo el.gmo es.gmo fi.gmo fr.gmo it.gmo pt.gmo ru_RU.gmo sk.gmo uk_UA.gmo
GMSGFMT = /usr/bin/msgfmt
GNOME_DOC_UTILS_CFLAGS =  
GNOME_DOC_UTILS_LIBS =  
GREP = /bin/grep
GSTREAMER_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libxml2  
GSTREAMER_LIBS = -pthread -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lxml2 -lgthread-2.0 -lrt -lglib-2.0  
HELP_DIR = ${datadir}/gnome/help
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INSTOBJEXT = .mo
INTLLIBS = 
INTLTOOL_EXTRACT = /usr/bin/intltool-extract
INTLTOOL_MERGE = /usr/bin/intltool-merge
INTLTOOL_PERL = /usr/bin/perl
INTLTOOL_UPDATE = /usr/bin/intltool-update
JAY = no
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBSAMPLERATE_CFLAGS = 
LIBSAMPLERATE_LIBS = 
LIBTOOL = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave-libtool '$(SHELL) $(top_builddir)/libtool'
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = 
MAKEFLAGS = -s
MAKEINFO = ${SHELL} /home/thomas/banshee-community-extensions/missing --run makeinfo
MCS = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave mcs /usr/bin/gmcs
MKDIR_P = /bin/mkdir -p
MKINSTALLDIRS = ./mkinstalldirs
MONO = /usr/bin/mono
MONO_CFLAGS = -D_REENTRANT -pthread -I/usr/include/mono-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
MONO_LIBS = -pthread -lmono -ldl -lpthread -lm -lgthread-2.0 -lrt -lglib-2.0  
MONO_MODULE_CFLAGS = -D_REENTRANT -pthread -I/usr/include/mono-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
MONO_MODULE_LIBS = -pthread -lmono -ldl -lpthread -lm -lgthread-2.0 -lrt -lglib-2.0  
MSGFMT = /usr/bin/msgfmt
MSGFMT_OPTS = -c
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/nm -B
NMEDIT = 
NOTIFYSHARP_CFLAGS = -I:/usr/lib/pkgconfig/../../share/gapi-2.0/pango-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/atk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gdk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gtk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/glib-api.xml  
NOTIFYSHARP_LIBS = -r:/usr/lib/cli/notify-sharp-0.4/notify-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll  
NOTIFY_SHARP_CFLAGS = -I:/usr/lib/pkgconfig/../../share/gapi-2.0/pango-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/atk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gdk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/gtk-api.xml -I:/usr/lib/pkgconfig/../../share/gapi-2.0/glib-api.xml  
NOTIFY_SHARP_LIBS = -r:/usr/lib/cli/notify-sharp-0.4/notify-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll  
NUNIT_CFLAGS = 
NUNIT_CONSOLE = 
NUNIT_LIBS = 
OBJC = /bin/bash /home/thomas/banshee-community-extensions/build/m4/shave/shave objc 
OBJDUMP = objdump
OBJEXT = o
OMF_DIR = ${datadir}/omf
OTOOL = 
OTOOL64 = 
PACKAGE = banshee-community-extensions
PACKAGE_BUGREPORT = http://bugzilla.gnome.org/enter_bug.cgi?product=banshee&component=Community%20Extensions
PACKAGE_NAME = banshee-community-extensions
PACKAGE_STRING = banshee-community-extensions 2.0.1
PACKAGE_TARNAME = banshee-community-extensions
PACKAGE_URL = 
PACKAGE_VERSION = 2.0.1
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
POFILES =  de.po el.po es.po fi.po fr.po it.po pt.po ru_RU.po sk.po uk_UA.po
POSUB = po
PO_IN_DATADIR_FALSE = 
PO_IN_DATADIR_TRUE = 
Q = $(V:1=)
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
TAO_FREEGLUT_CFLAGS = 
TAO_FREEGLUT_LIBS = 
TAO_OPENGL_CFLAGS = 
TAO_OPENGL_LIBS = 
TAO_SDL_CFLAGS = 
TAO_SDL_LIBS = 
USE_NLS = yes
V = @
VERSION = 2.0.1
XGETTEXT = /usr/bin/xgettext
ZEITGEIST_SHARP_CFLAGS = 
ZEITGEIST_SHARP_LIBS = 
abs_builddir = /home/thomas/banshee-community-extensions/src/Foo1
abs_srcdir = /home/thomas/banshee-community-extensions/src/Foo1
abs_top_builddir = /home/thomas/banshee-community-extensions
abs_top_srcdir = /home/thomas/banshee-community-extensions
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = /usr/local
expanded_bindir = /usr/local/bin
expanded_datadir = /usr/local/share
expanded_libdir = /usr/local/lib
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/thomas/banshee-community-extensions/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
shavedir = /home/thomas/banshee-community-extensions/build/m4/shave
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
ASSEMBLY = Banshee.Foo1
LINK = $(BANSHEE_LIBS) -r:System.Data -r:Mono.Data.SqliteClient \
	$(am__append_1)
SOURCES = \
	Banshee.NoNoise/NoNoiseSource.cs \
	Banshee.NoNoise/NoNoiseSourceContents.cs \
	Bpm/BpmDetectJob.cs \
	Data/DataHandler.cs \
	Data/DataParser.cs \
	Data/NoNoiseDBHandler.cs \
	lastfm-sharp/Lib.cs \
	lastfm-sharp/RequestParameters.cs \
	lastfm-sharp/Scrobbling/AuthenticationFailureException.cs \
	lastfm-sharp/Scrobbling/BadAuthenticationDetailsException.cs \
	lastfm-sharp/Scrobbling/BadSessionException.cs \
	lastfm-sharp/Scrobbling/BannedClientException.cs \
	lastfm-sharp/Scrobbling/Connection.cs \
	lastfm-sharp/Scrobbling/Entry.cs \
	lastfm-sharp/Scrobbling/NowplayingTrack.cs \
	lastfm-sharp/Scrobbling/PlaybackSource.cs \
	lastfm-sharp/Scrobbling/Request.cs \
	lastfm-sharp/Scrobbling/ScrobbleManager.cs \
	lastfm-sharp/Scrobbling/ScrobbleMode.cs \
	lastfm-sharp/Scrobbling/ScrobblingException.cs \
	lastfm-sharp/Scrobbling/WrongTimeException.cs \
	lastfm-sharp/Services/Album.cs \
	lastfm-sharp/Services/AlbumImageSize.cs \
	lastfm-sharp/Services/AlbumSearch.cs \
	lastfm-sharp/Services/AlbumWiki.cs \
	lastfm-sharp/Services/Artist.cs \
	lastfm-sharp/Services/ArtistBio.cs \
	lastfm-sharp/Services/ArtistSearch.cs \
	lastfm-sharp/Services/AuthenticatedUser.cs \
	lastfm-sharp/Services/AuthenticationRequiredException.cs \
	lastfm-sharp/Services/Base.cs \
	lastfm-sharp/Services/Country.cs \
	lastfm-sharp/Services/Event.cs \
	lastfm-sharp/Services/EventAttendance.cs \
	lastfm-sharp/Services/Gender.cs \
	lastfm-sharp/Services/Global.cs \
	lastfm-sharp/Services/Group.cs \
	lastfm-sharp/Services/GroupMembers.cs \
	lastfm-sharp/Services/IHasImage.cs \
	lastfm-sharp/Services/IHasURL.cs \
	lastfm-sharp/Services/IHasWeeklyAlbumCharts.cs \
	lastfm-sharp/Services/IHasWeeklyArtistCharts.cs \
	lastfm-sharp/Services/IHasWeeklyTrackCharts.cs \
	lastfm-sharp/Services/ImageSize.cs \
	lastfm-sharp/Services/InvalidPageException.cs \
	lastfm-sharp/Services/IShareable.cs \
	lastfm-sharp/Services/ITaggable.cs \
	lastfm-sharp/Services/Library.cs \
	lastfm-sharp/Services/LibraryAlbum.cs \
	lastfm-sharp/Services/LibraryAlbums.cs \
	lastfm-sharp/Services/LibraryArtist.cs \
	lastfm-sharp/Services/LibraryArtists.cs \
	lastfm-sharp/Services/LibraryItem.cs \
	lastfm-sharp/Services/LibraryTrack.cs \
	lastfm-sharp/Services/LibraryTracks.cs \
	lastfm-sharp/Services/Pages.cs \
	lastfm-sharp/Services/PastEvents.cs \
	lastfm-sharp/Services/Period.cs \
	lastfm-sharp/Services/Playlist.cs \
	lastfm-sharp/Services/Recipients.cs \
	lastfm-sharp/Services/RecommendedArtists.cs \
	lastfm-sharp/Services/RecommendedEvents.cs \
	lastfm-sharp/Services/Request.cs \
	lastfm-sharp/Services/Search.cs \
	lastfm-sharp/Services/ServiceException.cs \
	lastfm-sharp/Services/Session.cs \
	lastfm-sharp/Services/SiteLanguage.cs \
	lastfm-sharp/Services/Tag.cs \
	lastfm-sharp/Services/TagCollection.cs \
	lastfm-sharp/Services/TagSearch.cs \
	lastfm-sharp/Services/Tasteometer.cs \
	lastfm-sharp/Services/TopAlbum.cs \
	lastfm-sharp/Services/TopArtist.cs \
	lastfm-sharp/Services/TopFan.cs \
	lastfm-sharp/Services/TopItem.cs \
	lastfm-sharp/Services/TopTag.cs \
	lastfm-sharp/Services/TopTrack.cs \
	lastfm-sharp/Services/Track.cs \
	lastfm-sharp/Services/TrackSearch.cs \
	lastfm-sharp/Services/TrackWiki.cs \
	lastfm-sharp/Services/User.cs \
	lastfm-sharp/Services/Venue.cs \
	lastfm-sharp/Services/VenuePastEvents.cs \
	lastfm-sharp/Services/VenueSearch.cs \
	lastfm-sharp/Services/WeeklyAlbumChart.cs \
	lastfm-sharp/Services/WeeklyAlbumChartItem.cs \
	lastfm-sharp/Services/WeeklyArtistChart.cs \
	lastfm-sharp/Services/WeeklyArtistChartItem.cs \
	lastfm-sharp/Services/WeeklyChart.cs \
	lastfm-sharp/Services/WeeklyChartItem.cs \
	lastfm-sharp/Services/WeeklyChartTimeSpan.cs \
	lastfm-sharp/Services/WeeklyTrackChart.cs \
	lastfm-sharp/Services/WeeklyTrackChartItem.cs \
	lastfm-sharp/Services/Wiki.cs \
	lastfm-sharp/Services/XSPF.cs \
	lastfm-sharp/Utilities.cs \
	MathLib/Collection.cs \
	MathLib/Combinatorics.cs \
	MathLib/Complex.cs \
	MathLib/Constants.cs \
	MathLib/Distributions/Continuous/BetaDistribution.cs \
	MathLib/Distributions/Continuous/CauchyLorentzDistribution.cs \
	MathLib/Distributions/Continuous/ChiDistribution.cs \
	MathLib/Distributions/Continuous/ChiSquareDistribution.cs \
	MathLib/Distributions/Continuous/ContinuousUniformDistribution.cs \
	MathLib/Distributions/Continuous/ErlangDistribution.cs \
	MathLib/Distributions/Continuous/ExponentialDistribution.cs \
	MathLib/Distributions/Continuous/FisherSnedecorDistribution.cs \
	MathLib/Distributions/Continuous/GammaDistribution.cs \
	MathLib/Distributions/Continuous/LaplaceDistribution.cs \
	MathLib/Distributions/Continuous/LognormalDistribution.cs \
	MathLib/Distributions/Continuous/NormalDistribution.cs \
	MathLib/Distributions/Continuous/ParetoDistribution.cs \
	MathLib/Distributions/Continuous/StableDistribution.cs \
	MathLib/Distributions/Continuous/StandardDistribution.cs \
	MathLib/Distributions/Continuous/StudentsTDistribution.cs \
	MathLib/Distributions/Continuous/TriangularDistribution.cs \
	MathLib/Distributions/ContinuousDistribution.cs \
	MathLib/Distributions/CumulativeNormalDistribution.cs \
	MathLib/Distributions/Discrete/ArbitraryDistribution.cs \
	MathLib/Distributions/Discrete/BernoulliDistribution.cs \
	MathLib/Distributions/Discrete/BinomialDistribution.cs \
	MathLib/Distributions/Discrete/DiscreteUniformDistribution.cs \
	MathLib/Distributions/Discrete/GeometricDistribution.cs \
	MathLib/Distributions/Discrete/HypergeometricDistribution.cs \
	MathLib/Distributions/Discrete/PoissonDistribution.cs \
	MathLib/Distributions/Discrete/ZipfDistribution.cs \
	MathLib/Distributions/DiscreteDistribution.cs \
	MathLib/Distributions/IContinuousGenerator.cs \
	MathLib/Distributions/IContinuousProbabilityDistribution.cs \
	MathLib/Distributions/IDiscreteGenerator.cs \
	MathLib/Distributions/IDiscreteProbabilityDistribution.cs \
	MathLib/Distributions/InvCumulativeNormalDistribution.cs \
	MathLib/IRealFunction.cs \
	MathLib/LinearAlgebra/CholeskyDecomposition.cs \
	MathLib/LinearAlgebra/ComplexMatrix.cs \
	MathLib/LinearAlgebra/ComplexVector.cs \
	MathLib/LinearAlgebra/EigenvalueDecomposition.cs \
	MathLib/LinearAlgebra/IMatrix.cs \
	MathLib/LinearAlgebra/IVector.cs \
	MathLib/LinearAlgebra/LUDecomposition.cs \
	MathLib/LinearAlgebra/Matrix.cs \
	MathLib/LinearAlgebra/NamespaceDoc.cs \
	MathLib/LinearAlgebra/QRDecomposition.cs \
	MathLib/LinearAlgebra/SingularValueDecomposition.cs \
	MathLib/LinearAlgebra/Vector.cs \
	MathLib/Natural.cs \
	MathLib/Number.cs \
	MathLib/OnDemandComputation.cs \
	MathLib/Polynomial.cs \
	MathLib/Properties/Resources.Designer.cs \
	MathLib/Quaternion.cs \
	MathLib/RandomSources/AdditiveLaggedFibonacciRandomSource.cs \
	MathLib/RandomSources/MersenneTwisterRandomSource.cs \
	MathLib/RandomSources/RandomSource.cs \
	MathLib/RandomSources/SystemRandomSource.cs \
	MathLib/RandomSources/XorShiftRandomSource.cs \
	MathLib/Rational.cs \
	MathLib/Ratios.cs \
	MathLib/SampleList.cs \
	MathLib/Set.cs \
	MathLib/SiConstants.cs \
	MathLib/SiPrefixes.cs \
	MathLib/Sorting.cs \
	MathLib/SpecialFunctions.cs \
	MathLib/Statistics/Accumulator.cs \
	MathLib/Statistics/Histogram.cs \
	MathLib/Trigonometry.cs \
	MathLib/Tuple.cs \
	Mirage/Analyzer.cs \
	Mirage/AudioDecoder.cs \
	Mirage/Dbg.cs \
	Mirage/Matrix.cs \
	Mirage/Mfcc.cs \
	Mirage/Scms.cs \
	Mirage/ScmsConfiguration.cs \
	Mirage/Vector.cs \
	PCA/PCAnalyzer.cs

RESOURCES = \
	Foo1.addin.xml \
	Mirage/Resources/dct.filter \
	Mirage/Resources/filterweights.filter


# Initializers
MONO_BASE_PATH = 
MONO_ADDINS_PATH = 

# All extensions are libraries
TARGET = library
DIR_BIN = $(top_builddir)/bin

# Install Paths
DEFAULT_INSTALL_DIR = $(pkglibdir)
EXTENSIONS_INSTALL_DIR = $(DEFAULT_INSTALL_DIR)/Extensions
UNIQUE_FILTER_PIPE = tr [:space:] \\n | sort | uniq
BUILD_DATA_DIR = $(top_builddir)/bin/share/$(PACKAGE)
SOURCES_BUILD = $(addprefix $(srcdir)/, $(SOURCES)) \
	$(top_srcdir)/src/AssemblyInfo.cs
RESOURCES_EXPANDED = $(addprefix $(srcdir)/, $(RESOURCES))
RESOURCES_BUILD = $(foreach resource, $(RESOURCES_EXPANDED), \
	-resource:$(resource),$(notdir $(resource)))

INSTALL_ICONS = $(top_srcdir)/build/private-icon-theme-installer "$(mkinstalldirs)" "$(INSTALL_DATA)"
THEME_ICONS_SOURCE = $(wildcard $(srcdir)/ThemeIcons/*/*/*.png) $(wildcard $(srcdir)/ThemeIcons/scalable/*/*.svg)
THEME_ICONS_RELATIVE = $(subst $(srcdir)/ThemeIcons/, , $(THEME_ICONS_SOURCE))
ASSEMBLY_EXTENSION = $(strip $(patsubst library, dll, $(TARGET)))
ASSEMBLY_FILE = $(top_builddir)/bin/$(ASSEMBLY).$(ASSEMBLY_EXTENSION)
INSTALL_DIR_RESOLVED = $(firstword $(subst , $(DEFAULT_INSTALL_DIR), $(INSTALL_DIR)))
#ENABLE_TESTS_FLAG = "-define:ENABLE_TESTS"
FILTERED_LINK = $(shell echo "$(LINK)" | $(UNIQUE_FILTER_PIPE))
DEP_LINK = $(shell echo "$(LINK)" | $(UNIQUE_FILTER_PIPE) | sed s,-r:,,g | grep '$(top_builddir)/bin/')
OUTPUT_FILES = \
	$(ASSEMBLY_FILE) \
	$(ASSEMBLY_FILE).mdb

moduledir = $(EXTENSION_DIR)
module_SCRIPTS = $(OUTPUT_FILES)
EXTRA_DIST = $(SOURCES_BUILD) $(RESOURCES_EXPANDED) $(THEME_ICONS_SOURCE)
CLEANFILES = $(OUTPUT_FILES) TestResult.xml
DISTCLEANFILES = *.pidb
MAINTAINERCLEANFILES = Makefile.in
all: all-am

.SUFFIXES:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/build/build.mk $(top_srcdir)/build/build.environment.mk $(top_srcdir)/build/build.rules.mk $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/Foo1/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/Foo1/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-moduleSCRIPTS: $(module_SCRIPTS)
	@$(NORMAL_INSTALL)
	test -z "$(moduledir)" || $(MKDIR_P) "$(DESTDIR)$(moduledir)"
	@list='$(module_SCRIPTS)'; test -n "$(moduledir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(moduledir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(moduledir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-moduleSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(module_SCRIPTS)'; test -n "$(moduledir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(moduledir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(moduledir)" && rm -f $$files

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
tags: TAGS
TAGS:

ctags: CTAGS
CTAGS:


distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(SCRIPTS)
installdirs:
	for dir in "$(DESTDIR)$(moduledir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f Makefile
distclean-am: clean-am distclean-generic

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-moduleSCRIPTS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-moduleSCRIPTS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) uninstall-hook
.MAKE: install-am install-data-am install-strip uninstall-am

.PHONY: all all-am check check-am clean clean-generic clean-libtool \
	distclean distclean-generic distclean-libtool distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-data-hook install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-moduleSCRIPTS install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
	ps ps-am uninstall uninstall-am uninstall-hook \
	uninstall-moduleSCRIPTS


#test: $(ASSEMBLY_FILE)
#	if test "x$(TEST_ASSEMBLY)" = "xyes"; then \
#		LD_LIBRARY_PATH="$(BANSHEE_LIBDIR):$(BANSHEE_EXTDIR):$(EXTENSION_DIR)/..:$(EXTENSION_DIR)${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}" \
#		MONO_PATH="$(BANSHEE_LIBDIR):$(BANSHEE_EXTDIR):$(EXTENSION_DIR)/..:$(EXTENSION_DIR)${MONO_PATH+:$MONO_PATH}" \
#		$(NUNIT_CONSOLE) -nologo -noshadow $(ASSEMBLY_FILE); \
#	fi

test:

check: test

all: $(ASSEMBLY_FILE) theme-icons

run: 
	@pushd $(top_builddir); \
	make run \
	popd;

build-debug:
	@echo $(DEP_LINK)

$(ASSEMBLY_FILE).mdb: $(ASSEMBLY_FILE)

$(ASSEMBLY_FILE): $(SOURCES_BUILD) $(RESOURCES_EXPANDED) $(DEP_LINK)
	@mkdir -p $(top_builddir)/bin
	$(MCS) \
		$(GMCS_FLAGS) \
		$(ENABLE_TESTS_FLAG) \
		$(ASSEMBLY_BUILD_FLAGS) \
		-debug -target:$(TARGET) -out:$@ \
		$(BUILD_DEFINES) \
		$(FILTERED_LINK) $(RESOURCES_BUILD) $(SOURCES_BUILD)
	@if [ -e $(srcdir)/$(notdir $@.config) ]; then \
		cp $(srcdir)/$(notdir $@.config) $(top_builddir)/bin; \
	fi;
	@if [ ! -z "$(EXTRA_BUNDLE)" ]; then \
		cp $(EXTRA_BUNDLE) $(top_builddir)/bin; \
	fi;

theme-icons: $(THEME_ICONS_SOURCE)
	@$(INSTALL_ICONS) -il "$(BUILD_DATA_DIR)" "$(srcdir)" $(THEME_ICONS_RELATIVE)

install-data-hook: $(THEME_ICONS_SOURCE)
	@$(INSTALL_ICONS) -i "$(DESTDIR)$(pkgdatadir)" "$(srcdir)" $(THEME_ICONS_RELATIVE)
	$(EXTRA_INSTALL_DATA_HOOK)

uninstall-hook: $(THEME_ICONS_SOURCE)
	@$(INSTALL_ICONS) -u "$(DESTDIR)$(pkgdatadir)" "$(srcdir)" $(THEME_ICONS_RELATIVE)
	$(EXTRA_UNINSTALL_HOOK)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
